/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = require('./webpack.base.config')({
  mode: 'development',
  // Add hot reloading in development
  entry: {
    index: './src/index.tsx',
  },

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'public/index.html',
      hash: true, //防止缓存
      chunksSortMode: 'none', //如果使用webpack4将该配置项设置为'none'
      minify: {
        removeAttributeQuotes: true, //压缩 去掉引号
      },
    }),
    new CircularDependencyPlugin({
      include: 'src',
      exclude: /node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',

  performance: {
    hints: false,
  },
});
